name: Get tag

on:
  create:
    tags:
#      - '**v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag and Version
        run: |
          ls
          cd src
          ls
          cd ..
          ls
          TAG=${GITHUB_REF:10}
          ENVIRONMENT=$(echo "$TAG"|cut -d\- -f3)
          RELEASE_VERSION=$(echo "$TAG"|cut -d\- -f4)
          echo $ENVIRONMENT
          echo $RELEASE_VERSION

