name: Get tag

on:
  create:
    tags:
      'release-gcp-*-*.*.*'
env:
  ENVIRONMENT: ''
  RELEASE_VERSION: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag and Version
        run: |
          TAG=${GITHUB_REF:10}
          ENVIRONMENT=$(echo "$TAG"|cut -d\- -f3)
          RELEASE_VERSION=$(echo "$TAG"|cut -d\- -f4)
      - name: If Dev
        if: ENVIRONMENT == 'dev'
        run: echo "qa"
      - name: If Version
        if: ENVIRONMENT == 'qa'
        run: echo "qa"