name: Get tag

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo $RELEASE_VERSION