name: Get tag

on:
  create:
    tags:
      - 'release-gcp-*-*.*.*'

env:
  den: 'den'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag and Version
        run: |
          TAG=${GITHUB_REF:10}
          ENVIRONMENT=$(echo "$TAG"|cut -d\- -f3)
          RELEASE_VERSION=$(echo "$TAG"|cut -d\- -f4)
          den=$ENVIRONMENT
          echo $den
          echo $RELEASE_VERSION