name: Get Tag Invalid

on:
  push:
    tags:
    - den-tanik-[0-9]+.[0-9]+

env:
  environ: 'denis'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environ
        run: |
          $environ = 'tanik'
      - name: Print Environ
          echo $environ