name: Get Tag Invalid

on:
  push:
    tags:
    - den-*-[0-9]+.[0-9]+

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.RUN_SA_KEY }}
  kafka_dev: d.d.d.d
  kafka_qa: qa.qa.qa.qa

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Set Environ
        working-directory: ./src/main
        run: |
          echo $key
          tanik=$(echo $tag|cut -d\- -f3)
          echo $tanik
      - name: Checkout Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run App
        run: |
          ENV=$(echo $tag|cut -d\- -f2)
          echo ${{ env.kafka_echo ${{ENV}} }}
          sed -i 's/ip_address/${{ env.kafka_echo ${{ENV}} }}/g' src/main/resources/application.yaml
          cat src/main/resources/application.yaml