name: Get Tag Invalid

on:
  push:
    tags:
    - den-tanik-[0-9]+.[0-9]+

env:
  tag: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environ
        run: |
          version = $(echo $tag|cut -d\- -f3)
          echo $version
