name: Get Tag Invalid

on:
  push:
    tags:
    - den-tanik-[0-9]+.[0-9]+

env:
  environ: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Environ
        run: |
          tag=${GITHUB_REF:10}
          env.environ = $(echo $tag|cut -d\- -f2)
      - name: Print Environ
        run: echo env.environ