name: Get Tag Invalid

on:
  push:
    tags:
    - den-tanik-[0-9]+.[0-9]+

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.RUN_SA_KEY }}
  kafka_dev: kdev
  kafka_qa: kqa

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Set Environ
        working-directory: ./src/main
        run: |
          echo $key
          tanik=$(echo $tag|cut -d\- -f3)
          echo $tanik
      - name: Checkout Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run App
        run: |
          ENVIRONMENT=$(echo $tag|cut -d\- -f3)
          echo "Setting up environment: $ENVIRONMENT"
          if [ $ENVIRONMENT == 'dev' ]; then
          sed -i '' 's/ip_address/$kafka_dev/g' src/main/resources/application.yaml
          elif [ $ENVIRONMENT == 'qa' ]; then
          sed -i '' 's/ip_address/$kafka_qa/g' src/main/resources/application.yaml
          fi
          cat src/main/resources/application.yaml