name: Get Tag Invalid

on:
  push:
    tags:
    - den-tanik-[0-9]+.[0-9]+

env:
  environ: ${{ github.ref|cut -d\- -f2 }}
  version: ${{ github.ref|cut -d\- -f3}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environ
        run: |
          echo $environ
          echo $version

