name: Get Tag Invalid

on:
  push:
    tags:
    - den-tanik-[0-9]+.[0-9]+

env:
  tag: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environ
        working-directory: ./src/main
        run: |
          tanik=$(echo $tag|cut -d\- -f3)
          echo $tanik
          ls
