name: Get Tag Invalid

on:
  push:
    tags:
    - den-dev-[0-9]+.[0-9]+

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.RUN_SA_KEY }}
  ENVIRONMENT: ${{ $tag|cut -d\- -f2 }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Environ
        run: |
          echo environment $ENVIRONMENT





















